name: Publish package to npm

on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@zerogachis'

            - name: Update package version
              run: npm version --no-git-tag-version ${{ github.ref_name }}

            - name: Publish
              if: startsWith(github.ref, 'refs/tags/')
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}