name: Publish package to npm

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
          scope: "@zerogachis"

      - name: install libraries
        run: npm ci

      - name: Update package version
        run: npm version --no-git-tag-version ${{ github.ref_name }}

      - name: Compile
        run: npm run tsc

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: True
